[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
palette = "0.7.6"

[dependencies.iced]
features = ["advanced", "canvas", "lazy", "tokio"]
version = "0.13"
